### ISSUE TITLE
Add support for waiting for element to be clickable, visible and clickable

### ISSUE THREAD

**Issue by mrmattyboy1** [DockStudios/jmon#50]
See:
 * https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html#selenium.webdriver.support.expected_conditions.element_to_be_clickable
 * https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html#selenium.webdriver.support.expected_conditions.presence_of_element_located
 * https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html#selenium.webdriver.support.expected_conditions.visibility_of_element_located

**Comment by mrmattyboy1** [comment]
Also: https://stackoverflow.com/questions/59130200/selenium-wait-until-element-is-present-visible-and-interactable#answer-59130336

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/jmon/jmon/-/issues/132
gitlab-issue-id:132

**Comment by MatthewJohn** [comment]
This was released in 4.20.0
